{% set name = "ipynb-py-convert" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9749d5e5cc5275b62c3e8859e02192f4b734f79d91f57a34cd02eeb09c290254

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ipynb_py_convert

about:
  home: https://github.com/kiwi0fruit/ipynb-py-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter .ipynb notebooks and vice versa"
  doc_url: https://github.com/kiwi0fruit/ipynb-py-convert
  dev_url: https://github.com/kiwi0fruit/ipynb-py-convert

extra:
  recipe-maintainers:
    - kiwi0fruit
