{% set name = "ipynb-py-convert" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2025ef0e0b3ef7f63f60848305a33c232cf64704c65a5e3f15ae33f582f44520

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ipynb_py_convert

about:
  home: https://github.com/kiwi0fruit/ipynb-py-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter .ipynb notebooks and vice versa"
  doc_url: https://github.com/kiwi0fruit/ipynb-py-convert
  dev_url: https://github.com/kiwi0fruit/ipynb-py-convert

extra:
  recipe-maintainers:
    - kiwi0fruit
